---
abstract: 'DBIx::Class based session engine for Dancer'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  DBICx::TestDatabase: 0
  DBIx::Class::TimeStamp: 0
  Test::More: 0.63
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Session-DBIC
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Class: 0
  Dancer2: 0.14
  JSON: 0
  Scalar::Util: 0
  Try::Tiny: 0.01
resources:
  bugtracker: https://github.com/interchange/Dancer2-Session-DBIC/issues
  repository: https://github.com/interchange/Dancer2-Session-DBIC.git
version: 0.005
